global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
  - job_name: 'app-micrometer'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'app:8080' ]
  - job_name: 'app-otel'
    metrics_path: /
    static_configs:
      - targets: [ 'app:9464']